export const CONSTANT_MESSAGES = {

    DELETE_SUCCESSFULLY: "DELETE SUCCESSFULLY",
    DELETE_FAILED: "DELETE FAILED",
    UPDATE_FAILED: "UPDATE FAILED",
    UPDATE_SUCCESSFULLY: "UPDATE SUCCESSFULLY",
    USER_NOT_FOUND: "USER NOT FOUND",
    INVALID_PASSWORD: "INVALID PASSWORD",
    NOT_ALLOWED: "YOU ARE NOT ALLOWED",
    INVALID_TOKEN: "INVALID TOKEN PROVIDED",
    EXPIRED_TOKEN: "EXPIRED TOKEN PROVIDED",
    TOKEN_NOT_PROVIDED: "TOKEN NOT PROVIDED",

}
